#ifndef ACCOUNT_H
#define ACCOUNT_H

#include <QString>
#include <QDateTime>

namespace Models {

struct Account
{
    qint64 id = 0;
    qint64 user_id = 0;
    QString iban;
    QString balance = "0.00";
    QString currency;
    QString status = QStringLiteral("active");
    QDateTime created_at;
    QDateTime updated_at;
};

}
#endif // ACCOUNT_H

/*
neobank=# \d+ accounts
                                                                Table "public.accounts"
   Column   |           Type           | Collation | Nullable |             Default              | Storage  | Compression | Stats target | Description
------------+--------------------------+-----------+----------+----------------------------------+----------+-------------+--------------+-------------
 id         | integer                  |           | not null | generated by default as identity | plain    |             |              |
 user_id    | integer                  |           | not null |                                  | plain    |             |              |
 iban       | character varying(34)    |           |          |                                  | extended |             |              |
 balance    | numeric(18,2)            |           |          | 0                                | main     |             |              |
 currency   | character(3)             |           | not null |                                  | extended |             |              |
 status     | character varying(32)    |           |          | 'active'::character varying      | extended |             |              |
 created_at | timestamp with time zone |           |          | now()                            | plain    |             |              |
 updated_at | timestamp with time zone |           |          | now()                            | plain    |             |              |
Indexes:
    "accounts_pkey" PRIMARY KEY, btree (id)
    "accounts_iban_key" UNIQUE CONSTRAINT, btree (iban)
    "idx_accounts_user_id" btree (user_id)
Foreign-key constraints:
    "accounts_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
Referenced by:
    TABLE "transactions" CONSTRAINT "transactions_account_id_fkey" FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE
    TABLE "transactions" CONSTRAINT "transactions_counterparty_account_id_fkey" FOREIGN KEY (counterparty_account_id) REFERENCES accounts(id)
Access method: heap
*/
