#ifndef AUDITLOGENTRY_H
#define AUDITLOGENTRY_H

#include <QDateTime>
#include <QJsonObject>
#include <QString>
#include <QUuid>

namespace Models {

struct AuditLogEntry
{
    qint64 id = 0;
    QUuid session_id;
    qint64 user_id = 0;
    QString action;
    QJsonObject details;
    QDateTime created_at;
};

}

#endif // AUDITLOGENTRY_H

/*
                                                               Table "public.audit_log"
   Column   |           Type           | Collation | Nullable |             Default              | Storage  | Compression | Stats target | Description
------------+--------------------------+-----------+----------+----------------------------------+----------+-------------+--------------+-------------
 id         | bigint                   |           | not null | generated by default as identity | plain    |             |              |
 session_id | uuid                     |           |          |                                  | plain    |             |              |
 user_id    | integer                  |           |          |                                  | plain    |             |              |
 action     | character varying(64)    |           | not null |                                  | extended |             |              |
 details    | jsonb                    |           |          |                                  | extended |             |              |
 created_at | timestamp with time zone |           |          | now()                            | plain    |             |              |
Indexes:
    "audit_log_pkey" PRIMARY KEY, btree (id)
    "idx_audit_log_user_id" btree (user_id)
Foreign-key constraints:
    "audit_log_session_id_fkey" FOREIGN KEY (session_id) REFERENCES auth_sessions(id) ON DELETE SET NULL
    "audit_log_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
Access method: heap
*/
