#ifndef TRANSACTION_H
#define TRANSACTION_H

#include <QString>
#include <QDateTime>
#include <QJsonObject>

struct Transaction
{
    qint64 id = 0;
    qint64 account_id = 0;
    qint64 counterparty_account_id = 0;
    QString amount = "0.00"; //оказывается с++ не имеет типа decimal
    QString currency;
    QString type;
    QString description;
    QString status = QStringLiteral("pending");
    QJsonObject metadata;
    QDateTime created_at;
};
#endif // TRANSACTION_H

/*
neobank=# \d+ transactions
                                                                    Table "public.transactions"
         Column          |           Type           | Collation | Nullable |             Default              | Storage  | Compression | Stats target | Description
-------------------------+--------------------------+-----------+----------+----------------------------------+----------+-------------+--------------+-------------
 id                      | integer                  |           | not null | generated by default as identity | plain    |             |              |
 account_id              | integer                  |           | not null |                                  | plain    |             |              |
 counterparty_account_id | integer                  |           |          |                                  | plain    |             |              |
 amount                  | numeric(18,2)            |           | not null |                                  | main     |             |              |
 currency                | character(3)             |           | not null |                                  | extended |             |              |
 type                    | character varying(32)    |           | not null |                                  | extended |             |              |
 description             | text                     |           |          |                                  | extended |             |              |
 status                  | character varying(32)    |           |          | 'pending'::character varying     | extended |             |              |
 metadata                | jsonb                    |           |          | '{}'::jsonb                      | extended |             |              |
 created_at              | timestamp with time zone |           |          | now()                            | plain    |             |              |
Indexes:
    "transactions_pkey" PRIMARY KEY, btree (id)
    "idx_transactions_account_id" btree (account_id)
Foreign-key constraints:
    "transactions_account_id_fkey" FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE
    "transactions_counterparty_account_id_fkey" FOREIGN KEY (counterparty_account_id) REFERENCES accounts(id)
Access method: heap
*/
