#ifndef MODELS_USER_H
#define MODELS_USER_H

#include <QString>
#include <QDateTime>

namespace Models {

struct User
{
    qint64 id = 0;
    QString username;
    QString passwordHash;
    QString email;
    QString phone;
    QString status = QStringLiteral("active");
    QDateTime created_at;
    QDateTime updated_at;
};

}

#endif // USER_H

/*
                                                                   Table "public.users"
    Column     |           Type           | Collation | Nullable |             Default              | Storage  | Compression | Stats target | Description
---------------+--------------------------+-----------+----------+----------------------------------+----------+-------------+--------------+-------------
 id            | integer                  |           | not null | generated by default as identity | plain    |             |              |
 username      | character varying(64)    |           | not null |                                  | extended |             |              |
 password_hash | text                     |           | not null |                                  | extended |             |              |
 email         | character varying(320)   |           |          |                                  | extended |             |              |
 phone         | character varying(32)    |           |          |                                  | extended |             |              |
 status        | character varying(32)    |           |          | 'active'::character varying      | extended |             |              |
 created_at    | timestamp with time zone |           |          | now()                            | plain    |             |              |
 updated_at    | timestamp with time zone |           |          | now()                            | plain    |             |              |
Indexes:
    "users_pkey" PRIMARY KEY, btree (id)
    "users_username_key" UNIQUE CONSTRAINT, btree (username)
Check constraints:
    "email_validation" CHECK (email IS NULL OR email::text ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'::text)
    "phone_validation" CHECK (phone IS NULL OR phone::text ~ '^\+?[0-9]{10,15}$'::text)
Referenced by:
    TABLE "accounts" CONSTRAINT "accounts_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
    TABLE "audit_log" CONSTRAINT "audit_log_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
    TABLE "auth_sessions" CONSTRAINT "auth_sessions_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
Access method: heap
*/
